<a href="https://colab.research.google.com/github/Kemisola2022/Ksola-Tutorial/blob/main/Kemisola_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Indentation in Python**

In [ ]:
for i in range(1,11):
 print(i)




1
2
3
4
5
6
7
8
9
10


In [ ]:
import math

In [ ]:
from math import pi

In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
'''This is also a
perfect example of
multi-line comments'''

'This is also a\nperfect example of\nmulti-line comments'

In [ ]:
"""This is also a
perfect example of
multi-line comments"""

'This is also a\nperfect example of\nmulti-line comments'

In [ ]:
x = input
y = input
Sum R = x + y



In [ ]:
x = input()

54


In [ ]:
x = input(45)


45Months


In [ ]:
x = 10
print(x)


10


In [ ]:
a,b,c=5,3,2
print(a)
print(b)
print(c)

5
3
2


In [ ]:
a,b,c,d=5,3,2,"Hello"
print(a)
print(b)
print(c)
print(d)


5
3
2
Hello


In [ ]:
x=39
print(type(x))

<class 'int'>


In [ ]:
x='Kemolala'
print(type(x))

<class 'str'>


In [ ]:
x=5
y=7
print(x+y)

12


In [ ]:
print(x**y)

78125


In [ ]:
print(x<=y)

True


In [ ]:
print(x==y)

False


In [ ]:
x=48
y=48
print(x==y)


True


In [ ]:
not(x < 5 and y < 10)

True

In [ ]:
x > 58 and y > 10

False

In [ ]:
print(x)

48


In [ ]:
my_string = 'Kemisola is here'
print(my_string)

Kemisola is here


In [ ]:
print(my_string[0])

K


In [ ]:
print(my_string[-4])

h


In [ ]:
print(my_string[1:5])

emis


In [ ]:
print(my_string[-0:5])

Kemis


In [ ]:
print(my_string[-4:-7])

In [ ]:
str1 = "I love"
str2 = " my babies"
print(str1 + str2)

I love my babies


In [ ]:
a,b,c,d = 5,3,2,'Hello'
print(a)
print(b)
print(c)

5
3
2


In [ ]:
x=y=z='same'
print(x)
print(y)
print(z)

same
same
same


In [ ]:
x=2
((x+12))


14

In [ ]:
14^2

12

In [ ]:
8//3

2

In [ ]:
my_string = 'google'
print(my_string[0])


g


In [ ]:
from collections import deque


In [ ]:
queue = deque(["Eric", "John", "Michael"])

In [ ]:
queue.append("Terry")

In [ ]:
queue.append("Graham")

In [ ]:
my_dictionary = {"knowledge": "Data Science","tool":"python","year":2020}

In [ ]:
for key in my_dictionary.keys():
  print(key)

knowledge
tool
year


In [ ]:
for value in my_dictionary.values():
  print(value)

Data Science
python
2020


In [ ]:
for item in my_dictionary.items():
  print(item)

('knowledge', 'Data Science')
('tool', 'python')
('year', 2020)


In [ ]:
print(len(my_dictionary))

3


In [ ]:
my_dictionary ["learn"] = True

In [ ]:
print(my_dictionary)

{'knowledge': 'Data Science', 'tool': 'python', 'year': 2020, 'learn': True}


In [ ]:
x = (2>5) == (3==6)
if x:
  print('x is True')
else:
    print('x is not')

x is True


In [ ]:

x=19
if x < 10:
  print('Good morning')
elif x<12:
  print('Soon time for lunch')
elif x<18:
  print("Good day")
elif x<22:
  print('Good evening')
else:
  print('Good night')

Good evening


In [ ]:
def function_name():
  print("Hello World, this is my first function")

In [ ]:
function_name()

Hello World, this is my first function


In [ ]:
def function_name():
  print("Orange is the new black")

In [ ]:
Question 1: Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn

Sample value of n is 5 

Expected Result : 615 (5+55+555)

In [ ]:
n = 5
n1 = str(n)
n2 = n1 + n1
print(n2)

55


In [ ]:
n3 = n2 + n1
print(n3)

555


In [ ]:
Result = int(n1) + int(n2) + int(n3)
print(Result)

615


In [ ]:
n = 5
n1 = str(n)
n2 = n1 + n1
n3 = n2 + n1
Result = int(n1) + int(n2) + int(n3)
print(Result)



615


In [ ]:
A = int(input("Enter a value"))
if A%2 == 0:
  print("The number is even")
else:
  print("The number is odd")

Enter a value11
The number is odd


In [ ]:
for i in range(2000,3200): 
  if i%7 == 0 and i%5 != 0:
    print(i,end=" ")

2002 2009 2016 2023 2037 2044 2051 2058 2072 2079 2086 2093 2107 2114 2121 2128 2142 2149 2156 2163 2177 2184 2191 2198 2212 2219 2226 2233 2247 2254 2261 2268 2282 2289 2296 2303 2317 2324 2331 2338 2352 2359 2366 2373 2387 2394 2401 2408 2422 2429 2436 2443 2457 2464 2471 2478 2492 2499 2506 2513 2527 2534 2541 2548 2562 2569 2576 2583 2597 2604 2611 2618 2632 2639 2646 2653 2667 2674 2681 2688 2702 2709 2716 2723 2737 2744 2751 2758 2772 2779 2786 2793 2807 2814 2821 2828 2842 2849 2856 2863 2877 2884 2891 2898 2912 2919 2926 2933 2947 2954 2961 2968 2982 2989 2996 3003 3017 3024 3031 3038 3052 3059 3066 3073 3087 3094 3101 3108 3122 3129 3136 3143 3157 3164 3171 3178 3192 3199 

In [ ]:
from math import factorial
print(factorial(8))

40320


In [ ]:
my_string = "hello team"
x = ""
for i in range(len(my_string)):
  if i%2 == 0:
    x = x + my_string[i]
print(x)

hlota


In [ ]:
my_list = [2*4*6*8]
print(my_list)

[384]


In [ ]:
dict1= {'a': 100, 'b': 200, 'c': 300}
print('dict 1')
dict2= {'a': 300, 'b': 200, 'd': 400}
print('dict 2')
mergedDict={**dict1,**dict2}
print("Merged dictionary is:")
print(mergedDict)

dict 1
dict 2
Merged dictionary is:
{'a': 300, 'b': 200, 'c': 300, 'd': 400}


In [ ]:
b=[2,5,7,9]
print(len(b))

4


In [ ]:
def test_5(a):
    if a < 5 :
        print(a,"is lower than 5")
    elif a == 5:
        print(a,"is equal to 5")
    else:
        print(a,'is higher than 5')
test_5(25) 

25 is higher than 5


In [ ]:
def subtract(x,y):
  x = 10
  y = 3
  return x-y
  print()

Question 1

In [ ]:
def max( x, y ):

    if x > y:

        return x

    return y

def maxx( x, y, z ):

    return max( x, max( y, z ) )

print("max number is ",maxx(3, 6, 90))

max number is  90


Q2: Write a function calculation() such that it can accept two variables and calculate the addition and subtraction of it. And also it must return both addition and subtraction in a single return call. For example: calculation(40, 10) should produce 50, 30

In [ ]:
def calculate(a, b):
    return a + b, a - b


answer = calculate(40, 10)
print(answer)

(50, 30)


Q3:  Write a function that sums the elements of a list of integers.

* Write a function that multiplies the elements of an integer list.

* Use the two functions to sum the elements whose position is an even number (0,2,4…) and multiply the rest.

In [ ]:
def Summation(num):
    Sum = 0
    for i in num:
        Sum = Sum + i
    return Sum

print(Summation([1, 2, 3, 4, 5, 6, 7, 8,9,10]))  

def Multiply(num):
    Prod = 1
    for i in num:
        Prod *= i
    return Prod

print(Multiply([1, 2, 3, 4, 5, 6, 7, 8,9,10]))    

num = [1, 2, 3, 4, 5, 6, 7, 8,9,10]

Newlist = list(filter(lambda x: x%2 == 0, num)) 

print(Summation(Newlist))

Newlist2 = list(filter(lambda x: x%2 !=0, num))

print(Multiply(Newlist2))

55
3628800
30
945


Q4: Write a Python program that accepts a hyphen-separated sequence of words as input and prints the words in a hyphen-separated sequence after sorting them alphabetically.

Sample Items : green-red-yellow-black-white

Expected Result : black-green-red-white-yellow

In [ ]:
items=[n for n in input().split('-')]
items.sort()
print('-'.join(items))

Write a Python program to convert an array to an ordinary list with the same items.

In [ ]:
from array import *
array_num = array('i', [1, 2, 3, 4, 5, 6, 7, 8])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 2, 3, 4, 5, 6, 7, 8])
Convert the said array to an ordinary list with the same items:
[1, 2, 3, 4, 5, 6, 7, 8]


Write a NumPy program to compute the sum of the diagonal element of a given array.

In [ ]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


Given an array of your choice, get all the values higher than X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
print("Original array: ")
print(x)
print("Values bigger than 2 =", x[x>2])
print("Their indices are ", np.nonzero(x > 2))

Original array: 
[[1 2]
 [3 5]]
Values bigger than 2 = [3 5]
Their indices are  (array([1, 1]), array([0, 1]))


Given two arrays A&B having the same shape. The task is to apply addition of A and B : C is the new array. 

In [ ]:
A = np.array([0, 1, 2])
B = np.array([5, 5, 5])
A + B

array([5, 6, 7])

In [ ]:
A = np.array([0, 1, 2])
B = np.array([5, 5, 5])
print("C =", A + B)

C = [5 6 7]


In [ ]:
open(r"C:\Users\adekemisola.martins\Downloads\python.txt","w+" )

<_io.TextIOWrapper name='C:\\Users\\adekemisola.martins\\Downloads\\python.txt' mode='w+' encoding='UTF-8'>

In [ ]:
N = open(r"C:\Users\adekemisola.martins\Downloads\python.txt","w+" )
print(N.read())

Write a Python program to read first n lines of a file. (try to use readlines() function)

In [ ]:
m = 9
with open(r"C:\Users\adekemisola.martins\Downloads\python.txt","w+" )as m:
  last_n_files = m.readlines()[-1:]

3. Write a Python program to read last n lines of a file

In [ ]:
N = int(input('Please enter the number lines you want to read from the file:'))
with open(r"C:\Users\adekemisola.martins\Downloads\python.txt", 'r') as m:
    Reading = m.readlines()
    for x in Reading[0:N]:
        print(x, end ='')

Please enter the number lines you want to read from the file:6


In [ ]:
N = int(input('Please enter the number lines you want to read from the file:'))
with open(r"C:\Users\adekemisola.martins\Downloads\python.txt", 'r') as m:
    Reading = m.readlines()
    for x in Reading[-N:]:
        print(x, end ='')

Please enter the number lines you want to read from the file:5


In [ ]:
N = 0
with open(r"C:\Users\adekemisola.martins\Downloads\python.txt", 'r') as m:
    data = m.read()
    Split_Read = data.split()
    N += len(Split_Read)

print(N)

0


Display numbers from -10 to -1 using for loop

In [3]:
for number in range(-10,0):
  print(number)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


Given a number count the total number of digits in a number, for example, the number is 75869, so the output should be 5

In [5]:
count = 0
n = 75869
n = str(n)
for number in range(len(n)):
  count = number + 1
print(count)   


5


Write a function which Displays the cube of the number up to a given integer, for example the number is 2 the cube should be 8

In [6]:
def i(y):
  result = y*y*y
  return result
i(2)  

8

Given two integer numbers return their product. If the product is greater than 1000, then return their sum

In [9]:
x = 5
y = 23
if(x*y) > 1000:
  print(x*y)
else:
  print(x+y)  


28


In [16]:
def cabrat(x,y):
  prod = x*y
  s = x+y
  if prod > 1000:
    return s
  else:
    return prod
cabrat(140,10)    





150

Given a list of numbers, return True if first and last number of a list is same

In [23]:
list1 = [2,4,5,6,8,21]
list2 = [3,5,9,13,21,21]
if list1[0] == list2[-1]:
  print(True)
else:
 print(False)
 


False


Given a two list of numbers create a new list such that new list should contain only odd numbers from the first list and even numbers from the second list, for example list1 =  [10, 20, 23, 11, 17] and list 2 = [13, 43, 24, 36, 12]  => result should be [23, 11, 17, 24, 36, 12]

In [26]:
list1 = [10, 20, 23, 11, 17]
list2 = [13, 43, 24, 36, 12] 
list3 = []
for n in range((len(list1))):
  if list1[n]%2 != 0:
    list3.append(list1[n])
for n in range((len(list2))):
  if list2[n]%2 == 0:
    list3.append(list2[n])
print(list3)


[23, 11, 17, 24, 36, 12]


Write a function which Iterates a given list and counts the occurrence of each element and creates a dictionary to show the count of each element, for example: input list  [11, 45, 8, 11, 23, 45, 23, 45, 89]=> result should be {11: 2, 45: 3, 8: 1, 23: 2, 89: 1}

In [27]:
from collections import Counter

In [28]:
x =  [11, 45, 8, 11, 23, 45, 23, 45, 89]
y = Counter(x)
print(y)

Counter({45: 3, 11: 2, 23: 2, 8: 1, 89: 1})


Write a function which finds the intersection of two sets and removes common elements from the first set. for example: First Set  {65, 42, 78, 83, 23, 57, 29} and Second Set  {67, 73, 43, 48, 83, 57, 29} => Intersection should be  {57, 83, 29} and First Set after removing common element  {65, 42, 78, 23}

In [30]:
x =  {65, 42, 78, 83, 23, 57, 29}
y = {67, 73, 43, 48, 83, 57, 29}
v = x & y
print(x-v)

{65, 42, 78, 23}
